version: '3'

services:
  jupyterhub:
    build: 
      context: ./jupyterhub
      dockerfile: ./Dockerfile
    container_name: jupyterhub_hub   # The service will use this container name.
    volumes:                         # Give access to Docker socket.
      - /var/run/docker.sock:/var/run/docker.sock
    environment:                     # Env variables passed to the Hub process.
      DOCKER_JUPYTER_IMAGE: jupyterlab_img
      DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_default
      HUB_IP: jupyterhub_hub
    networks:
      - web
    labels:                          # Traefik configuration.
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:jupyterhub.nanpower.me"
      - "traefik.basic.protocol=http"

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    command: echo

networks:
  web:
    external: true
